### ISSUE TITLE
Doesn't work for EV SSL's

### ISSUE THREAD

**Issue by bgold0** [spatie/ssl-certificate-chain-resolver#3]
This seems like a GREAT application, but it doesn't work for EV SSL Certificates. It marks them as invalid.

**Comment by freekmurze** [comment]
Could you send me the certificate that you are having trouble with?

**Comment by bgold0** [comment]
Via email okay?

**Comment by freekmurze** [comment]
that's fine!

**Comment by bgold0** [comment]
Just sent, thank you for taking a look!

**Comment by freekmurze** [comment]
Received it. I could verify that the certificate you sent is indeed marked as invalid. I'll take a closer look at the problem soon and will let you know when it will be fixed.

**Comment by bgold0** [comment]
Awesome, I appreciate your time!

**Comment by felnne** [comment]
Hi I just came across this problem myself, it would be great if there was a fix.

Happy to provide my certificate if needed.

**Comment by freekmurze** [comment]
I verified that the package does indeed not work for EV SSL's. Fixing this isn't high on the priority list because I don't need it myself. I welcome a PR requests that adds this.
